In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
import pathlib
import pandas as pd
import numpy as np
import torch
import pickle

In [0]:
path = pathlib.Path('./drive/My Drive/Kaggle/Titanic')
path

PosixPath('drive/My Drive/Kaggle/Titanic')

In [0]:
df = pd.read_csv(path/'train.csv')

In [0]:
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [0]:
df.drop(columns=['Name'], inplace=True)

In [0]:
df.head()

PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked
0            1         0       3  ...   7.2500    NaN         S
1            2         1       1  ...  71.2833    C85         C
2            3         1       3  ...   7.9250    NaN         S
3            4         1       1  ...  53.1000   C123         S
4            5         0       3  ...   8.0500    NaN         S

[5 rows x 11 columns]

In [0]:
sex_dict = {'male':1, 'female':2} 

In [0]:
df['Sex'] = df['Sex'].map(sex_dict)

In [0]:
df.head()

PassengerId  Survived  Pclass  Sex  ...            Ticket     Fare  Cabin Embarked
0            1         0       3    1  ...         A/5 21171   7.2500    NaN        S
1            2         1       1    2  ...          PC 17599  71.2833    C85        C
2            3         1       3    2  ...  STON/O2. 3101282   7.9250    NaN        S
3            4         1       1    2  ...            113803  53.1000   C123        S
4            5         0       3    1  ...            373450   8.0500    NaN        S

[5 rows x 11 columns]

In [0]:
df.drop(columns=['Cabin', 'Ticket'], inplace=True)

In [0]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    1  22.0      1      0   7.2500        S
1            2         1       1    2  38.0      1      0  71.2833        C
2            3         1       3    2  26.0      0      0   7.9250        S
3            4         1       1    2  35.0      1      0  53.1000        S
4            5         0       3    1  35.0      0      0   8.0500        S

In [0]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [0]:
embark_dict = {'S':1, 'C':2, 'Q':3, np.nan:0}

In [0]:
df['Embarked'] = df['Embarked'].map(embark_dict)

In [0]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         1
1            2         1       1    2  38.0      1      0  71.2833         2
2            3         1       3    2  26.0      0      0   7.9250         1
3            4         1       1    2  35.0      1      0  53.1000         1
4            5         0       3    1  35.0      0      0   8.0500         1

In [0]:
df['Embarked'].unique()

array([1, 2, 3, 0])

In [0]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [0]:
df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [0]:
df.fillna(-99999)

PassengerId  Survived  Pclass  Sex  ...  SibSp  Parch     Fare  Embarked
0              1         0       3    1  ...      1      0   7.2500         1
1              2         1       1    2  ...      1      0  71.2833         2
2              3         1       3    2  ...      0      0   7.9250         1
3              4         1       1    2  ...      1      0  53.1000         1
4              5         0       3    1  ...      0      0   8.0500         1
..           ...       ...     ...  ...  ...    ...    ...      ...       ...
886          887         0       2    1  ...      0      0  13.0000         1
887          888         1       1    2  ...      0      0  30.0000         1
888          889         0       3    2  ...      1      2  23.4500         1
889          890         1       1    1  ...      0      0  30.0000         2
890          891         0       3    1  ...      0      0   7.7500         3

[891 rows x 9 columns]

In [0]:
df['Fare'].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [0]:
import random

In [0]:
df['Pclass'].unique()

array([3, 1, 2])

In [0]:
pclass_onehot = torch.zeros(len(df), 3)

In [0]:
pclass_onehot.scatter_(1, torch.tensor(df['Pclass']-1).unsqueeze(1), 1)

tensor([[0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        ...,
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.]])

In [0]:
df['Sex'].unique()

array([1, 2])

In [0]:
sex_onehot = torch.zeros(len(df), 2)
sex_onehot.scatter_(1, torch.tensor(df['Sex']-1).unsqueeze(1), 1)

tensor([[1., 0.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [1., 0.],
        [1., 0.]])

In [0]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [0]:
df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [0]:
parch_onehot = torch.zeros(len(df), 7)
parch_onehot.scatter_(1, torch.tensor(df['Parch']).unsqueeze(1), 1)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 1.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])

In [0]:
df['Embarked'].unique()

array([1, 2, 3, 0])

In [0]:
embark_onehot = torch.zeros(len(df), 4)
embark_onehot.scatter_(1, torch.tensor(df['Embarked']).unsqueeze(1), 1)

tensor([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        ...,
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [0]:
survival_onehot = torch.zeros(len(df), 2)
survival_onehot.scatter_(1, torch.tensor(df['Survived']).unsqueeze(1), 1)

tensor([[1., 0.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [0., 1.],
        [1., 0.]])

In [0]:
label_tensor = survival_onehot

In [0]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         1
1            2         1       1    2  38.0      1      0  71.2833         2
2            3         1       3    2  26.0      0      0   7.9250         1
3            4         1       1    2  35.0      1      0  53.1000         1
4            5         0       3    1  35.0      0      0   8.0500         1

In [0]:
df.drop(columns=['PassengerId', 'Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'], inplace=True)

In [0]:
df.head()

Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [0]:
df['Age'] = df['Age'].replace(-99999, 0)

In [0]:
feature_tensor = torch.tensor(df.values)

In [0]:
feature_tensor

tensor([[22.0000,  7.2500],
        [38.0000, 71.2833],
        [26.0000,  7.9250],
        ...,
        [ 0.0000, 23.4500],
        [26.0000, 30.0000],
        [32.0000,  7.7500]], dtype=torch.float64)

In [0]:
mean = feature_tensor.mean(dim=0)
var = feature_tensor.var(dim=0)
mean, var

(tensor([23.7993, 32.2042], dtype=torch.float64),
 tensor([ 309.6218, 2469.4368], dtype=torch.float64))

In [0]:
for i in range(0,len(feature_tensor)):
    if feature_tensor[i,0] == 0:
        feature_tensor[i,0] = mean[0]

In [0]:
feature_tensor

tensor([[22.0000,  7.2500],
        [38.0000, 71.2833],
        [26.0000,  7.9250],
        ...,
        [23.7993, 23.4500],
        [26.0000, 30.0000],
        [32.0000,  7.7500]], dtype=torch.float64)

In [0]:
mean = feature_tensor.mean(dim=0)
var = feature_tensor.var(dim=0)
mean, var

(tensor([28.5271, 32.2042], dtype=torch.float64),
 tensor([ 174.5997, 2469.4368], dtype=torch.float64))

In [0]:
feature_tensor = (feature_tensor-mean)/(var**0.5)

In [0]:
feature_tensor

tensor([[-0.4940, -0.5022],
        [ 0.7169,  0.7864],
        [-0.1912, -0.4886],
        ...,
        [-0.3578, -0.1762],
        [-0.1912, -0.0444],
        [ 0.2628, -0.4921]], dtype=torch.float64)

In [0]:
label = torch.cat([feature_tensor,parch_onehot.to(dtype=torch.float64),pclass_onehot.to(dtype=torch.float64),sex_onehot.to(dtype=torch.float64),embark_onehot.to(dtype=torch.float64)], dim=1)

In [0]:
label

tensor([[-0.4940, -0.5022,  1.0000,  ...,  1.0000,  0.0000,  0.0000],
        [ 0.7169,  0.7864,  1.0000,  ...,  0.0000,  1.0000,  0.0000],
        [-0.1912, -0.4886,  1.0000,  ...,  1.0000,  0.0000,  0.0000],
        ...,
        [-0.3578, -0.1762,  0.0000,  ...,  1.0000,  0.0000,  0.0000],
        [-0.1912, -0.0444,  1.0000,  ...,  0.0000,  1.0000,  0.0000],
        [ 0.2628, -0.4921,  1.0000,  ...,  0.0000,  0.0000,  1.0000]],
       dtype=torch.float64)

In [0]:
len(label[0])

18

In [0]:
len(label)

891

In [0]:
with open(path/'feature_tensor.pickle', 'wb') as f:
    pickle.dump(label, f)

with open(path/'label_tensor.pickle', 'wb') as f:
    pickle.dump(label_tensor, f)

# fin